Disable other processing

diff --git a/.github/workflows/update_issue_open.yaml b/.github/workflows/update_issue_open.yaml
--- a/.github/workflows/update_issue_open.yaml
+++ b/.github/workflows/update_issue_open.yaml
@@ -26,57 +26,57 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-      - name: Authenticate with AWS
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{secrets.AWS_REGION}}
-      - name: Login to AWS ECR
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v2
-        with:
-          registry-type: public
-      - name: Build, tag, and push docker image to Amazon ECR
-        id: build-push
-        env:
-          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          REGISTRY_ALIAS: compfuzzci
-          REPOSITORY: compfuzzci-dafny
-          IMAGE: dafny-lang-master
-          AUTHOR: dafny-lang
-          BRANCH: master
-        run: |
-          max_attempts=5
-          attempt=0
-          success=false
-          while [ $attempt -lt $max_attempts ]; do
-            attempt=$((attempt + 1))
-            echo "Attempt $attempt of $max_attempts"
+      # - name: Authenticate with AWS
+      #   uses: aws-actions/configure-aws-credentials@v4
+      #   with:
+      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      #     aws-region: ${{secrets.AWS_REGION}}
+      # - name: Login to AWS ECR
+      #   id: login-ecr
+      #   uses: aws-actions/amazon-ecr-login@v2
+      #   with:
+      #     registry-type: public
+      # - name: Build, tag, and push docker image to Amazon ECR
+      #   id: build-push
+      #   env:
+      #     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+      #     REGISTRY_ALIAS: compfuzzci
+      #     REPOSITORY: compfuzzci-dafny
+      #     IMAGE: dafny-lang-master
+      #     AUTHOR: dafny-lang
+      #     BRANCH: master
+      #   run: |
+      #     max_attempts=5
+      #     attempt=0
+      #     success=false
+      #     while [ $attempt -lt $max_attempts ]; do
+      #       attempt=$((attempt + 1))
+      #       echo "Attempt $attempt of $max_attempts"
             
-            docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE \
-              -f Docker/dafny.Dockerfile \
-              --build-arg AUTHOR=$AUTHOR \
-              --build-arg BRANCH=$BRANCH . && \
-            docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE
+      #       docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE \
+      #         -f Docker/dafny.Dockerfile \
+      #         --build-arg AUTHOR=$AUTHOR \
+      #         --build-arg BRANCH=$BRANCH . && \
+      #       docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE
             
-            if [ $? -eq 0 ]; then
-              success=true
-              break
-            else
-              echo "Attempt $attempt failed. Retrying..."
-            fi
-          done
+      #       if [ $? -eq 0 ]; then
+      #         success=true
+      #         break
+      #       else
+      #         echo "Attempt $attempt failed. Retrying..."
+      #       fi
+      #     done
           
-          if [ $success = true ]; then
-            echo "Build and push successful after $attempt attempts."
-            echo "build-successful=true" >> "$GITHUB_OUTPUT"
-          else
-            echo "Build and push failed after $attempt attempts."
-            echo "build-successful=false" >> "$GITHUB_OUTPUT"
-            exit 1
-          fi
-  ProcessBug:
+      #     if [ $success = true ]; then
+      #       echo "Build and push successful after $attempt attempts."
+      #       echo "build-successful=true" >> "$GITHUB_OUTPUT"
+      #     else
+      #       echo "Build and push failed after $attempt attempts."
+      #       echo "build-successful=false" >> "$GITHUB_OUTPUT"
+      #       exit 1
+      #     fi
+  # ProcessBug:
     runs-on: ubuntu-latest
     needs: BuildImage
     if: needs.BuildImage.outputs.build-successful == 'true'
